baseURL = 'https://nishanth-bs.github.io/Logs'
relativeURLs = false
canonifyURLs = true
uglyURLs = false
languageCode = 'en-us'
title = 'Decoded With Nishanth'
theme = 'PaperMod'

[params]
  author = "Nishanth"
  showReadingTime = true
  showShareButtons = true
  defaultTheme = "auto"

[permalinks]
  posts = "/:slug/"