baseURL = 'https://nishanth-bs.github.io/'
relativeURLs = true
canonifyURLs = true
languageCode = 'en-us'
title = 'Decoded With Nishanth'
theme = 'PaperMod'

[params]
  author = "Nishanth"
  showReadingTime = true
  showShareButtons = true
  defaultTheme = "auto"